- .github/workflows/build.yml
- server/.env.example
- server/devind/settings.py
- Секретный ключ шифрования вынесен в переменные окружения.
- Образ собирается только при создании релиза.
> Вынос ключа шифрования в переменные окружения, осуществление сбора образа при теггировании

- client/package.json
- client/pages/auth/cbias/_uid.vue
- client/tailwind.config.js
При авторизации через портал cbias.ru осуществляется перенаправление на проекты сборов
> Переадресация на проект сборов после авторизации через портал cbias.ru

- server/devind/settings.py
Идентификатор приложения при авторизации через портал cbias.ru изменен на `61`.
> Установлен идентификатор приложения

- client/pages/dcis/documents/_documentId.vue
- client/pages/dcis/periods/_periodId.vue
- client/pages/dcis/periods/_periodId/documents.vue
- client/pages/dcis/periods/_periodId/index.vue
- client/pages/dcis/projects/_projectId/periods.vue
Добавлен элемент индикации загрузки документов, добавлены некоторые оформительные правки.
> Добавлен элемент индикации загрузки документа

- client/components/common/MutationResultAlert.vue
- client/components/common/forms/MutationForm.vue
- client/components/common/forms/MutationModalForm.vue
- client/components/dcis/projects/AddProject.vue
- client/components/global/FooterComponent.vue
- client/components/global/ThemeColor.vue
- client/composables/filters.ts
- server/apps/dcis/schema/mutations/project_mutations.py
- server/apps/dcis/validators.py
Некоторые файлы переписаны на composition api. Это связано с постепенной миграцией на vue3, nuxt3&
> Проведен некоторый рефакторинг системных файлов на клиенте

- client/components/dcis/Grid.vue
- client/gql/dcis/mutations/sheet/add_row_dimension.graphql
- client/gql/dcis/mutations/sheet/delete_row_dimension.graphql
- client/schema.graphql
- client/types/graphql.d.ts
- server/apps/dcis/schema/mutations/sheet_mutations.py
- Добавлена минимальная ширина колонки.
- Добавлены обновления мердженых ячеек.
> Исправлено добавление строки при объединенных строках

- server/apps/dcis/schema/mutations/document_mutations.py
- server/apps/dcis/schema/mutations/project_mutations.py
- server/apps/dcis/schema/mutations/sheet_mutations.py
- server/apps/dcis/schema/queries/document_queries.py
- server/apps/dcis/schema/queries/project_queries.py
- server/apps/dcis/schema/types.py
- server/apps/dcis/services/excel_unload.py
Ошибка была связана с получением границ по ключу, которые не всегда были доступны.
> Исправлена ошибка экспорта файла

- client/components/dcis/Grid.vue
- client/components/dcis/grid/GridBody.vue
- client/components/dcis/grid/GridCell.vue
- client/components/dcis/grid/cells/GridCellDepartment.vue
- client/components/dcis/grid/cells/GridCellText.vue
- client/composables/grid.ts
- client/services/grid.ts
Реализовано множественное выделение ячеек, а также исправлены некоторые ошибки визуализации.
> Реализовано множественное выделение ячеек

- server/apps/dcis/models/document.py
- server/apps/dcis/schema/mutations/sheet_mutations.py
При удалении убран баг, который возникает когда не удаляется объединенной в одной ячейки.
> Исправлена проблема при удалении строк, которые содержат объединенный ячейки

- client/Dockerfile
Версия LTS обновлена до последней. Предупреждения при установке зависимостей скрыты при сборе образа.
> Обновлена версия nodejs. Скрыты warnings при установке зависимостей

- client/layouts/default.vue
Добавлено возвращение null в случае, если пользователь не авторизован
> Исправлена проблема получения идентификатора пользователя

- client/components/dcis/grid/GridBody.vue
Пока не разработаны миграции по изменению границ, отрисовка временна скрыта.
> На клиенте временно скрыта отрисовка границ

- client/pages/dcis/periods/_periodId.vue
- client/pages/dcis/periods/_periodId/attributes.vue
- client/pages/dcis/periods/_periodId/documents.vue
- client/pages/dcis/periods/_periodId/settings.vue
- client/pages/dcis/projects/_projectId.vue
- client/pages/dcis/projects/_projectId/accounts.vue
- client/pages/dcis/projects/_projectId/periods.vue
- client/pages/dcis/projects/_projectId/settings.vue
- client/pages/panel/ac.vue
При просмотре проектов и периодов добавлена бургер-кнопка для выбора левого меню при просмотре с телефона.
> Добавлена кнопка меню при просмотре с мобильного телефона

- client/composables/query-relay.ts
Переменные пагинации переписывают переданные переменные
> Исправлена проблема с пагинацией

- client/Dockerfile
По всей видимости баш на локальной машине и баш в actions разный.
> Исправлена проблема с установлением зависимостей при сборке клиентского контейнера

- server/Dockerfile
- server/whitelist.txt
Так приложение собирается каждый раз заново, то мы и копируем весь код каждый раз.
> Изменен механизм сборки серверного docker контейнера

- client/components/dcis/Grid.vue
- client/components/dcis/grid/GridBody.vue
- client/components/dcis/grid/GridCell.vue
- client/components/dcis/grid/GridHeader.vue
- client/components/dcis/grid/GridSheetToolbar.vue
- client/components/dcis/grid/controls/GridRowControl.vue
- client/composables/grid.ts
- client/nuxt.config.ts
- client/package.json
- client/plugins/detect-browser.ts
- client/services/grid.ts
- client/tsconfig.json
- client/types/grid-types.ts
> Исправлены стили для фиксированного первого столбца, добавлено выделение для строк и столбцов

- client/components/dcis/Grid.vue
- client/components/dcis/grid/GridBody.vue
- client/components/dcis/grid/GridHeader.vue
- client/components/dcis/grid/controls/GridRowControl.vue
- client/composables/grid.ts
- client/static/cursors/arrow-down.svg
- client/static/cursors/arrow-right.svg
> Сделано массовое выделение строк и столбцов

- client/components/dcis/grid/controls/GridRowControl.vue
- client/gql/dcis/queries/document.graphql
Теперь вместе со строкой на клиенте удаляются cells и values. Также осуществлен мелкий рефакторинг, удалены лишние find и any. Closes #226.
> Исправлен баг при удалении строки

- client/components/dcis/grid/cells/GridCellClassification.vue
- client/gql/dcis/mutations/cell/add_budget_classification.graphql
- client/schema.graphql
- client/types/graphql.d.ts
- server/apps/dcis/schema/__init__.py
- server/apps/dcis/schema/mutations/__init__.py
- server/apps/dcis/schema/mutations/cell_mutations.py
- server/poetry.lock
Если КБК не найдено, предлагается сервис для добавления.
> Сделано добавления КБК, которые не найдены в поиске

- client/composables/query-common.ts
- client/composables/query-relay.ts
- client/composables/query-result.ts
- client/yarn.lock
Функция в официальной библиотеке устарела, поэтому вынесена в проект
> Функция получения результат вынесена в проект

- .gitlab-ci.yml
- server/poetry.lock
В связи с предстоящим переездом на гитлаб добавлены скрипт сборки на оснвое тегов.
> Добавлены скрипт ci/di для сборки контейнеров на гитлабе

- client/pages/panel/ac/groups.vue
- client/pages/panel/ac/users.vue
- server/poetry.lock
Кроме этого, был исправлен баг, связанный с назначеним привилегий в группы.
> Исправлены баги при назначении пользователю группу

- client/components/pages/PageView.vue
- client/gql/pages/queries/pages.graphql
- client/pages/categories/_categoryId.vue
- client/pages/categories/_categoryId/add_page.vue
- client/pages/categories/_categoryId/index.vue
Не передавался требуемый параметр
> Исправлена дополнительная подгрузка страниц

- server/apps/dcis/schema/mutations/project_mutations.py
Теперь пользователь добавляется при создании проекта
> При добавлении проекта, добавляется пользователь

- client/components/dcis/grid/GridSheetToolbar.vue
- server/apps/dcis/helpers/cell.py
- server/apps/dcis/services/value_services.py
> Исправить проблему с расчетами формул при обновлении ячеек

- client/components/dcis/periods/AddPeriodDivisions.vue
- client/lang/ru/dcis.ts
- client/pages/dcis/periods/_periodId.vue
- client/pages/dcis/periods/_periodId/divisions.vue
> Дивизион заменен на конкретную привязку

- client/components/dcis/documents/DocumentStatuses.vue
- client/lang/ru/dcis.ts
> Добавлена функция подтверждения удаления статуса версии документа

- client/pages/dcis/periods/_periodId/sheets.vue
> Исправлено переключение листов в таблице периода

- client/components/dcis/Grid.vue
- client/gql/dcis/queries/document.graphql
- client/pages/dcis/documents/_documentId.vue
- client/pages/dcis/periods/_periodId/sheets.vue
- client/types/graphql.d.ts
> feat: добавлены хлебные крошки и карточка для документа

- client/components/dcis/grid/GridCell.vue
- client/components/dcis/grid/cells/GridCellFiles.vue
- client/lang/ru/dcis.ts
> Сделан просмотр файла без редактирования

- client/components/dcis/documents/DocumentStatuses.vue
- client/components/dcis/documents/DocumentStatusesReadonly.vue
- client/lang/ru/dcis.ts
- client/pages/dcis/periods/_periodId/documents.vue
> Сделано отображение статусов документа при отсутствии прав на изменение

- server/apps/dcis/helpers/cell.py
Я думаю, он тут не ожидает None в словаре, т.к. с None ломалось и в прошлый раз, и после того как я исправил тогда пустую строку. То же условие ломается, т.к. тогда не могло прочитать первый символ у None, а сейчас тоже не может слайс на None сделать. Если дописать дополнительное условие на None то оно проходит, но работает так же, как если вообще ничего не передавать. И я думаю, что предполагалось не вообще не передавать такой ключ. Например следующий тест проходит, хоть ключа F2 вообще нет.
Поэтому я отфильтровал None. Не знаю что это за проверка на лист, но вроде не должна логика сломаться. И теперь оно пересчитывает и когда нет и Value и Cell.default = None, а раньше ломалось.
> Поправлен расчет формул

- server/apps/dcis/services/sheet_unload_services.py
Closes #596.
Проблема была в том, что сервер выдавал ячейки в неправильном порядке.
> Исправлено неправильное выделение широкой таблицы

- client/components/dcis/documents/AddDocument.vue
- server/apps/dcis/services/sheet_services.py
> Исправлено неправильное добавление дочерних строк

- client/components/dcis/projects/AddProject.vue
> Поправлена форма добавления проекта

- client/pages/dcis/documents/_documentId.vue
> Убрано избыточное дублирование названия учреждения

- docs/docs/document_rules.md
- server/apps/dcis/services/project_services.py
- server/apps/dcis/tests/permissions/document_permissions.py
- server/apps/dcis/tests/services/project_services.py
> Cделано скрытие проекта

- client/components/dcis/periods/PeriodGroupPrivileges.vue
> Выведены все разрешения

- client/components/dcis/grid/GridSheetToolbar.vue
- client/components/dcis/projects/AddPeriod.vue
- client/composables/grid-mutations.ts
- client/gql/dcis/mutations/period/add_period.graphql
- client/lang/ru/dcis.ts
- client/schema.graphql
- client/services/grid.ts
- client/types/graphql.d.ts
- client/types/grid.ts
- server/apps/dcis/schema/mutations/period_mutations.py
- server/apps/dcis/services/excel_extractor_services.py
- server/apps/dcis/services/period_services.py
- server/apps/dcis/services/sheet_services.py
> Сделано редактирование readonly для ячейки

- client/components/profile/BasicInformation.vue
- client/pages/profile/me.vue
Информация удалена, а не закоментирована, потому как может быть легко восстановлена из гита
> Убрана возможность изменения информации, которая забирается с портала

- client/middleware/redirect-auth.ts
- client/pages/auth/login.vue
- client/pages/auth/logout.vue
- client/pages/index.vue
- client/stores/auth-store.ts
- server/poetry.lock
Реализована новая middleware для переадресации на внешние ресурсы.
Добавлен setTimeout для перенаправления удаления авторизационного токена после отправки запроса на разлогинивание.
> Поправлена переадресация на сервер авторизации

- client/.eslintrc.js
- client/components/dcis/periods/AddPeriodDivisionsFromFile.vue
- client/components/dcis/periods/AddPeriodDivisionsFromPeriod.vue
- client/components/dcis/periods/AddPeriodDivisionsMenu.vue
- client/gql/dcis/mutations/period/add_divisions_form_period.graphql
- client/lang/ru/dcis.ts
- client/package.json
- client/pages/dcis/periods/_periodId/divisions.vue
- client/pages/dcis/projects/index.vue
- client/schema.graphql
- client/types/graphql.d.ts
- client/yarn.lock
- server/apps/dcis/schema/mutations/period_mutations.py
- server/apps/dcis/services/period_services.py
В RP реализован импорт файлов из смешных периодов в этом же проекте
> Импорт дивизионов из предыдущих периодов

- client/components/dcis/grid/GridSheetToolbar.vue
- client/components/dcis/grid/GridSheets.vue
- client/components/global/AppBar.vue
- client/middleware/redirect-auth.ts
> Скрыт тулбар для режима редактирования документа

- client/components/dcis/periods/AddPeriodDivisions.vue
- server/apps/dcis/services/divisions_services.py
> Улучшен поиск дивизионов

- client/pages/index.vue
На сервере функционал не работает должным образом
> Исправлен баг при переадресации с главной страницы

- client/components/dcis/grid/GridBody.vue
- client/components/dcis/grid/GridHeader.vue
- server/apps/dcis/helpers/cell.py
Closes #729.
Также поправлена небольшая ошибка выделения.
> Сделано отображение ошибок в формулах

- client/components/common/filters/ItemsDataFilter.vue
- client/components/dcis/grid/GridHeader.vue
- client/components/dcis/grid/GridSheetToolbar.vue
- client/lang/ru/dcis.ts
- client/pages/dcis/periods/_periodId/documents.vue
Closes #736.
Автоматическое скрытие черновиков для кураторов отложено до добавления функционала связанного с кураторами.
> Cделан фильтр документов по статусу

- client/components/dcis/grid/Grid.vue
- client/components/dcis/grid/GridBody.vue
> Изменен фон у ячеек readonly

- client/pages/dcis/periods/_periodId/documents.vue
> Поправлен фильтр дивизионов

- server/apps/dcis/services/add_document_data_services.py
0 - falsy тип, поэтому пропускался
> Исправлен пропуск значений с 0

- server/apps/dcis/tests/services/status_services.py
Closes #963. Сумма работает, добавил дополнительный тест для проверки только. Нужно указывать название листа только перед первой ячейкой в диапазонах.
> Доработка ограничений

- server/apps/dcis/services/divisions_services.py
- server/apps/dcis/tests/services/divisions_services.py
> Исправлено отображение организаций у кураторов

- client/composables/query-common.ts
- client/composables/query-relay.ts
- client/pages/dcis/projects/_projectId/periods.vue
- client/pages/dcis/projects/index.vue
> Исправлено удаление проектов и периодов

- client/components/dcis/grid/GridCell.vue
Пока не стал делать отдельную настройку, сделал такое ограничение только для текста
> Переносы строк учитываются только в текстовом режиме
